server:
  # 服务端口
  port: 17001

spring:
  application:
    # 应用名称
    name: eureka-client

eureka:
  client:
    # Eureka服务端地址
    service-url:
      # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
      defaultZone: http://localhost:17000/eureka

